[project]
name = "alarm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "py-cord>=2.6.1",
    "pydub>=0.25.1",
    "python-dotenv>=0.21.1",
    "simpleaudio>=1.0.4",
]
